name: Build BananaOS

on:
  push:
    branches:
      - main
      - IA32-EFI
      - x86_64
  pull_request:
    branches:
      - main
      - IA32-EFI
      - x86_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential nasm gcc-multilib binutils \
                            grub-common grub-pc-bin xorriso mtools

    - name: Build portable image
      run: |
        make clean
        make buildPortable

    - name: Build setup ISO
      run: make buildSetup

    - name: Upload portable image artifact
      uses: actions/upload-artifact@v4
      with:
        name: bananaos-${{ github.ref_name }}-portable
        path: bananaos.img

    - name: Upload setup ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: bananaos-${{ github.ref_name }}-setup
        path: setup.iso
